#!/bin/bash
### Make chains master script
# Antomatically generated by make_chains.py on 2024-11-15 17:31:17.168236

export PATH=/project/daane/hussain/programs/make_lastz_chains/doLastzChains:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/HL_scripts:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/HL_kent_binaries:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/kent_binaries:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/GenomeAlignmentTools/src:$PATH

/project/daane/hussain/programs/make_lastz_chains/doLastzChains/doLastzChain.pl /project/daane/hussain/final_project/make_lastz_chains/obeta_ragtag_ncbi/chain_obeta_cgob/DEF -clusterRunDir /project/daane/hussain/final_project/make_lastz_chains/obeta_ragtag_ncbi/chain_obeta_cgob --executor slurm --queueSize 210 2>&1 | tee -a /project/daane/hussain/final_project/make_lastz_chains/obeta_ragtag_ncbi/chain_obeta_cgob/make_chains.log
