#!/bin/bash
### Make chains master script
# Antomatically generated by make_chains.py on 2024-02-26 12:21:05.591614

export PATH=/project/daane/hussain/programs/make_lastz_chains/doLastzChains:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/HL_scripts:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/HL_kent_binaries:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/kent_binaries:$PATH
export PATH=/project/daane/hussain/programs/make_lastz_chains/GenomeAlignmentTools/src:$PATH

/project/daane/hussain/programs/make_lastz_chains/doLastzChains/doLastzChain.pl /project/daane/hussain/repeatmask/batrachoidiformes/opsanus_beta/chain_obet_cgob/DEF -clusterRunDir /project/daane/hussain/repeatmask/batrachoidiformes/opsanus_beta/chain_obet_cgob --executor slurm --queueSize 210 2>&1 | tee -a /project/daane/hussain/repeatmask/batrachoidiformes/opsanus_beta/chain_obet_cgob/make_chains.log
